configure tweaks

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,15 +1,39 @@
 #!/bin/sh
 set -e
 
-echo "--- [hdf5lib] Starting Unix configuration (STATIC) ---"
+echo "--- [hdf5lib] Starting Windows/Unix configuration (STATIC) ---"
 
 # Input directories
 WD="$(pwd)"
 ZLIB_SRC="$WD/src/zlib-1.3.1"
 HDF5_SRC="$WD/src/hdf5-2.0.0"
+HDF5_BUILD="$WD/src/hdf5_build"
 
-# Define R executable path for readability
-R_EXE="${R_HOME}/bin/R"
+# Find R
+R_EXE="${R_HOME}/bin${R_ARCH_BIN}/R"
+if test -z "$R_EXE"; then
+  R_EXE="${R_HOME}/bin/R"
+  if test -z "$R_EXE"; then
+    R_EXE=`which R 2>/dev/null`
+    if test -z "$R_EXE"; then
+      echo "R was not found on the PATH. Please install R."
+      exit 1
+    fi
+  fi
+fi
+
+# Find cmake
+CMAKE_EXE=`which cmake3 2>/dev/null`
+if test -z "$CMAKE_EXE"; then
+  CMAKE_EXE=`which cmake 2>/dev/null`
+  if test -z "$CMAKE_EXE"; then
+    CMAKE_EXE=`which /Applications/CMake.app/Contents/bin/cmake 2>/dev/null`
+    if test -z "$CMAKE_EXE"; then
+      echo "CMake was not found on the PATH. Please install CMake."
+      exit 1
+    fi
+  fi
+fi
 
 # Get R's compiler/linker flags to ensure we respect the build environment
 R_CC=$("$R_EXE" CMD config CC)
@@ -57,7 +81,7 @@ mkdir -p "$HDF5_BUILD"
 cd "$HDF5_BUILD"
 
 # CMake Configuration
-cmake "$HDF5_SRC" \
+${CMAKE_EXE} "$HDF5_SRC" \
   -DCMAKE_BUILD_TYPE=Release \
   -DBUILD_SHARED_LIBS=OFF \
   -DBUILD_TESTING=OFF \
